import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('ai-grading:curriculum-scope:v1', 'bnu24-math-g8-upper'))
  await page.emulateMedia({ reducedMotion: 'reduce' })
})

test('real API skill edits, guarded dialogs and shared assembly basket persist', async ({ page }) => {
  const requests: string[] = []
  page.on('request', request => requests.push(new URL(request.url()).pathname))
  await page.goto('/question-bank?tab=skill')
  await expect(page.getByRole('heading', { name: '题库管理', exact: true })).toBeVisible()
  await expect(page.locator('.qb-skill-row').first()).toBeVisible()
  await expect(page.locator('.qb-question-card').first()).toBeVisible()
  await expect(page.locator('.page-tabs .is-active')).toHaveText('按技能')
  await expect(page.getByRole('checkbox', { name: '折叠重复题' })).toBeChecked()
  for (const width of [1440, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    const panes = await page.locator('.qb-skill-layout > .qb-browse-pane').evaluateAll(elements => elements.map(element => { const rect = element.getBoundingClientRect(); return { x: rect.x, y: rect.y, width: rect.width, height: rect.height } }))
    expect(panes).toEqual([{ x: 204, y: 72, width: 280, height: 808 }, { x: 498, y: 72, width: width - 522, height: 808 }])
    await page.screenshot({ path: `test-results/question-bank-browse-${width}.png` })
  }
  await page.getByRole('button', { name: '上传试卷', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '上传试卷与任务' })).toBeVisible()
  await page.getByRole('dialog', { name: '上传试卷与任务' }).getByRole('button', { name: '关闭', exact: true }).press('Escape')
  await expect(page.getByRole('button', { name: '上传试卷', exact: true })).toBeFocused()
  await page.getByRole('searchbox', { name: '搜题干' }).fill('LONG_FORMULA')
  await expect(page.locator('.qb-question-card')).toHaveCount(1)
  const heading = page.getByRole('button', { name: '第 1 题', exact: true })
  await heading.click()
  await expect(page.locator('.qb-annotation')).toBeVisible()
  await expect(page.locator('.qb-evidence-row')).toHaveCount(2)
  await expect(page.locator('.qb-inline-card__heading')).toHaveCSS('position', 'sticky')
  for (const width of [1440, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
    expect(await page.locator('.qb-question-pane').evaluate(el => el.getBoundingClientRect().width)).toBeGreaterThan(940)
    await page.screenshot({ path: `test-results/question-bank-skill-${width}.png` })
  }
  expect(requests.filter(path => path === '/api/question-bank/questions/1')).toHaveLength(1)
  expect(requests.filter(path => path === '/api/question-bank/questions/1/solution-evidence')).toHaveLength(1)
  expect(requests.filter(path => path === '/api/question-bank/criteria/questions/1')).toHaveLength(1)
  await page.locator('.qb-inline-card.is-expanded .qb-card-menu summary').click()
  await page.locator('.qb-inline-card.is-expanded .qb-card-menu summary').press('Escape')
  await expect(page.locator('.qb-inline-card.is-expanded .qb-card-menu')).not.toHaveAttribute('open')
  await expect(page.locator('.qb-annotation')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(heading).toBeFocused()
  await expect(page.locator('.qb-annotation')).toHaveCount(0)
  await heading.click()
  await page.getByText('编辑题目属性 / 选择小节', { exact: true }).click()
  await page.getByLabel('要添加的标签类别').selectOption('ability')
  await page.locator('.qb-tag-add').getByRole('button', { name: '添加', exact: true }).click()
  await page.getByLabel('能力标签值').last().fill('运算能力')
  await page.getByRole('button', { name: '保存标签', exact: true }).click()
  await expect(page.getByText('标签已经保存。', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '加入试卷篮', exact: true }).click()
  const basketButton = page.getByRole('button', { name: /试卷篮 · 1/ })
  await expect(basketButton).toBeVisible()
  await basketButton.click()
  await expect(page.getByRole('dialog').filter({ has: page.getByText('试卷篮 · 1', { exact: true }) })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(basketButton).toBeFocused()
  await page.getByRole('button', { name: '按试卷', exact: true }).click()
  const paperMenu = page.locator('.paper-card__more-toggle').first()
  await paperMenu.click()
  await page.getByRole('menuitem', { name: '编辑资料', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '编辑试卷资料' })).toBeVisible()
  await page.getByRole('dialog', { name: '编辑试卷资料' }).press('Escape')
  await expect(paperMenu).toBeFocused()
  await expect(page.getByRole('button', { name: '维护', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '待处理', exact: true }).click()
  const taxonomyButton = page.locator('.qb-todo-group').filter({ has: page.getByRole('heading', { name: '新词例外', exact: true }) }).getByRole('button', { name: '去处理 →' })
  await taxonomyButton.click()
  await expect(page.getByRole('dialog', { name: '标签治理', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(taxonomyButton).toBeFocused()
  await page.getByRole('button', { name: '按技能', exact: true }).click()
  await page.getByRole('searchbox', { name: '搜题干' }).fill('')
  await page.getByRole('button', { name: /未挂技能/ }).click()
  await expect(page.locator('.qb-skill-pane')).toBeVisible()
  await expect(page.locator('.qb-question-card')).toHaveCount(20)
  for (const width of [1440, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.locator('.qb-question-pane').evaluate(el => el.getBoundingClientRect().width)).toBe(width - 522)
    await page.screenshot({ path: `test-results/question-bank-unlinked-${width}.png` })
  }
  const repairButton = page.getByRole('button', { name: 'AI 补挂技能', exact: true })
  await repairButton.click()
  await expect(page.getByRole('dialog', { name: '只补缺失部分' })).toContainText('技能关联')
  await expect(page.getByRole('dialog', { name: '只补缺失部分' })).toContainText('逐题清单')
  await page.screenshot({ path: 'test-results/question-bank-repair-preview.png' })
  await page.keyboard.press('Escape')
  await expect(repairButton).toBeFocused()
  await page.goto('/question-assembly?mode=browse')
  await expect(page.locator('.page-tabs .is-active')).toHaveText('整理与导出')
  await expect(page.locator('.page-tabs button')).toHaveCount(2)
  await expect(page.locator('.assembly-editor__workspace')).toBeVisible()
  for (const width of [1440, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
    expect(await page.locator('.assembly-editor__workspace > *').evaluateAll(elements => elements.map(element => { const rect = element.getBoundingClientRect(); return { x: rect.x, y: rect.y, width: rect.width, height: rect.height } }))).toEqual([{ x: 204, y: 72, width: 280, height: 808 }, { x: 498, y: 72, width: width - 836, height: 808 }, { x: width - 324, y: 72, width: 300, height: 808 }])
    await page.screenshot({ path: `test-results/question-assembly-${width}.png` })
  }
  await page.getByRole('button', { name: '去题库选题', exact: true }).first().click()
  await expect(page).toHaveURL(/question-bank\?tab=skill/)
})

test('real API keeps all 2005 paper questions and restores the selected question', async ({ page }) => {
  await page.goto('/question-bank?tab=paper')
  await page.getByRole('button', { name: '按试卷', exact: true }).click()
  await page.getByRole('button', { name: '匿名九年级期末试卷', exact: true }).click()
  await expect(page.locator('.qb-paper-detail .qb-question-card')).toHaveCount(2005, { timeout: 60000 })
  await expect(page.locator('.qb-paper-detail .qb-number-nav button')).toHaveCount(2005)
  await page.locator('.qb-number-nav button').first().click()
  await expect(page.locator('.qb-paper-detail .qb-annotation')).toBeVisible()
  await expect(page).toHaveURL(/question=1/)
  await page.reload()
  await expect(page.locator('.qb-paper-detail .qb-annotation')).toBeVisible({ timeout: 60000 })
  await page.keyboard.press('Escape')
})

test('real API todo dialogs and paper jump preserve focus and responsive layout', async ({ page }) => {
  await page.goto('/question-bank?tab=todo')
  await page.getByRole('button', { name: '待处理', exact: true }).click()
  await expect(page.locator('.qb-todo-stats')).toContainText('分析未完成')
  await expect(page.locator('.qb-todo-group').first().getByRole('button', { name: '判定点批量审核' })).toBeVisible()
  const criteriaButton = page.getByRole('button', { name: '判定点批量审核', exact: true })
  await criteriaButton.click()
  await expect(page.getByRole('dialog', { name: '判定点待审核', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(criteriaButton).toBeFocused()
  expect(await page.locator('.qb-todo-group').evaluateAll(elements => elements.every(element => element.scrollHeight <= element.clientHeight + 1))).toBe(true)
  for (const width of [1440, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    await page.screenshot({ path: `test-results/question-bank-todo-${width}.png` })
  }
  await page.locator('.qb-todo-group').filter({ has: page.getByRole('heading', { name: /^未挂技能/ }) }).getByRole('button', { name: '去处理 →' }).first().click()
  await expect(page.locator('.qb-paper-detail .qb-annotation')).toBeVisible({ timeout: 60000 })
  await expect(page.locator('.qb-paper-detail .qb-inline-card.is-expanded .qb-inline-card__title')).toBeInViewport()
  for (const width of [1440, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
    await page.screenshot({ path: `test-results/question-bank-paper-${width}.png` })
  }
})
